change order
tpa-nextgen/modules-master pull request #48
Opened 2022-06-29 09:39 UTC by trainings-au

2022-06-30 05:58 UTC, manzoid requested changes

2022-06-30 05:58 UTC, manzoid commented on outlines/all_outlines_foundations.md
> + * The example app is a calorie counter app e.g. https://github.com/davidhealey/waistline
this seems way too hard doesn't it?  This is an Android app... how are they supposed to fix an Android app?

2022-06-30 05:58 UTC, manzoid commented on outlines/all_outlines_foundations.md
> +   * They follow clean code rules
This isn't the only reason is it? 

For example, seasoned programmers also know to pay a lot of attention to knowing about the problem domain, they don't just think about code. They select dependable tools. They code review well, and accept code review feedback well.  They design ahead of time, in writing. They actively seek design reviews.  Etc, etc.

Better to caveat as "One important reason: they follow clean code rules."

2022-06-30 05:58 UTC, manzoid commented on outlines/all_outlines_foundations.md
> +   * You don't need years of expirience to follow them
experience

2022-06-30 05:58 UTC, manzoid commented on outlines/all_outlines_foundations.md
> + * Debugging is early in the course - functions, lists, and maps are known.
Please list the points above that are being targeted by the Summative exercise.  

It shouldn't be _all_ of them, just some of them. 

We don't really need or particularly want to define the exact exercise and the exercise steps at the level of this outline.

2022-06-30 07:35 UTC, trainings-au commented on outlines/all_outlines_foundations.md
> + * The example app is a calorie counter app e.g. https://github.com/davidhealey/waistline
The idea is that this will be Python written by us. Just the business logic of the parts of the app.

2022-07-02 18:23 UTC, manzoid commented
merging, will edit directly, thanks.

2022-07-02 18:23 UTC, merged